//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SporSalonuProgrami.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Antreman
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Antreman()
        {
            this.KullaniciAntreman = new HashSet<KullaniciAntreman>();
        }
    
        public int ID { get; set; }
        public string Hareket { get; set; }
        public Nullable<int> SeviyeID { get; set; }
        public string Aciklama { get; set; }
    
        public virtual Seviye Seviye { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KullaniciAntreman> KullaniciAntreman { get; set; }
    }
}
