//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SporSalonuProgrami.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FirmaBilgileri
    {
        public int ID { get; set; }
        public string FirmaAdi { get; set; }
        public string Sehir { get; set; }
        public string Adres { get; set; }
        public string SirketNo { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string WebSitesi { get; set; }
    }
}
