//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SporSalonuProgrami.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SporSalonuEntities : DbContext
    {
        public SporSalonuEntities()
            : base("name=SporSalonuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Antreman> Antreman { get; set; }
        public virtual DbSet<FirmaBilgileri> FirmaBilgileri { get; set; }
        public virtual DbSet<KullaniciAntreman> KullaniciAntreman { get; set; }
        public virtual DbSet<Olculer> Olculer { get; set; }
        public virtual DbSet<Seviye> Seviye { get; set; }
        public virtual DbSet<UrunVeHizmetler> UrunVeHizmetler { get; set; }
        public virtual DbSet<Uyeler> Uyeler { get; set; }
        public virtual DbSet<Yonetici> Yonetici { get; set; }
        public virtual DbSet<YoneticiGirisi> YoneticiGirisi { get; set; }
        public virtual DbSet<Urunler> Urunler { get; set; }
    }
}
