//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SporSalonuProgrami.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Olculer
    {
        public int ID { get; set; }
        public Nullable<int> UyelerID { get; set; }
        public Nullable<int> Boy { get; set; }
        public Nullable<int> Kilo { get; set; }
        public Nullable<int> Omuz { get; set; }
        public Nullable<int> Kol { get; set; }
        public Nullable<int> Bel { get; set; }
        public Nullable<int> Kalca { get; set; }
        public Nullable<int> Bacak { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<int> Gogus { get; set; }
        public Nullable<bool> SilindiMi { get; set; }
    
        public virtual Uyeler Uyeler { get; set; }
    }
}
